-- AlterTable
ALTER TABLE "Game" ALTER COLUMN "startDay" SET DEFAULT '08:00:00',
ALTER COLUMN "endDay" SET DEFAULT '22:00:00';

-- AlterTable
ALTER TABLE "Player" ALTER COLUMN "state" SET DEFAULT 'ALIVE',
ALTER COLUMN "role" SET DEFAULT 'VILLAGER',
ALTER COLUMN "power" SET DEFAULT 'NONE';
